import { Metadata } from "next";
import { Roboto, JetBrains_Mono} from "next/font/google";
import "./globals.css";
import { CornerDownRight } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import Header from "@/content/Header";
import ThemeButton from "@/content/lightdark";
import { ThemeProvider } from "next-themes";

const mono = JetBrains_Mono({
  subsets: ["latin"],
});

const inter = Roboto({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Projeto Guarda-Rios", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <header className={`flex ${mono.className} bg-(--background-top-whitemode) justify-between items-center p-2 dark:bg-(--background-top)`}>
          <section>
            <Link href="/" className="flex items-center">
            <Image src="/guarda_rios_logo1.png" alt="logo" width={50} height={40}/>
            <span className="text-xl text-black font-bold dark:text-white">Projeto Guarda-Rios</span>
            </Link>
          </section>
         
          <section className={`flex ${inter.className} items-center gap-3 text-(--text2) font-bold`}>
            <Header />
            <Link href="https://data.guarda-rios.pt" className="flex gap-1 p-2 ml-5 text-white bg-(--green) rounded border border-2 border-(--green2) dark:bg-(--green2)/40 dark:border-(--green)/60">
            <CornerDownRight className="-mt-0.5"/>
            <span>Portal de Dados</span>
            </Link>
            <ThemeButton />
          </section>
        </header>

        <main className={`${inter.className} text-black dark:text-white`}>
          {children}
        </main>

        <footer className="min-w-full bg-black flex items-center justify-center items-center p-2 gap-5">
          <Link href="https://www.instagram.com/projeto_guardarios" className="invert">
            <Image src="/Instagram-Icon.svg" alt="Insta" width={20} height={20}/>
          </Link>
          
          <Link href="https://github.com/Projeto-Guarda-Rios" className="invert">
            <Image src="/GitHub.png" alt="Insta" width={20} height={20}/>
          </Link>

          <Link href="https://mail.google.com/" className="invert">
            <Image src="/Email-logo.png" alt="Insta" width={20} height={20}/>
          </Link>
        </footer>
        </body>
    </html>
  );
}
